### ISSUE TITLE
Cannot create new company when lib-company not available

### ISSUE THREAD

**Issue by mluppi** [cysec-platform/cysec-platform#24]
Cannot create new company when the coach `lib-company` is not available (in the `coaches` directory).

**Stacktrace:**
```
INFO [http-nio-8080-exec-4] eu.smesec.platform.auth.AuthFilter.filter Checking for user authentication
INFO [http-nio-8080-exec-4] eu.smesec.platform.auth.AbstractFilter.checkReqest Checking request
INFO [http-nio-8080-exec-4] eu.smesec.platform.auth.strategies.AbstractAuthStrategy.setupCompany Checking oauth credentials
INFO [http-nio-8080-exec-4] eu.smesec.platform.auth.strategies.AbstractAuthStrategy.setupCompany Creating first user anonymous in new company acme.
WARNING [http-nio-8080-exec-4] eu.smesec.platform.auth.strategies.AbstractAuthStrategy.setupCompany Default coach lib-company was not detected.
WARNING [http-nio-8080-exec-4] eu.smesec.platform.auth.AbstractFilter.checkReqest An error occurred accessing the cache
	eu.smesec.bridge.execptions.CacheNotFoundException: Company acme was not found
		at eu.smesec.platform.cache.DataCache.executeOnCompany(DataCache.java:92)
		at eu.smesec.platform.cache.CacheAbstractionLayer.readOnUsers(CacheAbstractionLayer.java:184)
		at eu.smesec.platform.cache.CacheAbstractionLayer.getUserByName(CacheAbstractionLayer.java:285)
		at eu.smesec.platform.auth.strategies.AbstractUserAuthStrategy.authenticate(AbstractUserAuthStrategy.java:47)
		at eu.smesec.platform.auth.AbstractFilter.checkReqest(AbstractFilter.java:80)
		at eu.smesec.platform.auth.AuthFilter.filter(AuthFilter.java:63)
```

---

_When the company coach is present, the company is created properly:_
```
[http-nio-8080-exec-2] eu.smesec.platform.cache.CompanyCache.install Created user file: {basepath}/data/cysec/acme/users.xml for company acme
[http-nio-8080-exec-2] eu.smesec.platform.cache.CompanyCache.install Created audit file: {basepath}/data/cysec/acme/audits.xml for company acme
[http-nio-8080-exec-2] eu.smesec.platform.cache.CompanyCache.install Created replika token file for company acme
[http-nio-8080-exec-2] eu.smesec.platform.cache.CompanyCache.getSource Loading cache: {basepath}/data/cysec/acme/users.xml
[http-nio-8080-exec-2] eu.smesec.platform.cache.CompanyCache.getSource Loaded  cache: {basepath}/data/cysec/acme/users.xml
[http-nio-8080-exec-2] eu.smesec.platform.cache.DataCache.addCompany Added new company acme
```

**Comment by martingwerder** [comment]
Not sure if I understand that one. lib-company contains the coach and subcoaches.These ressources are required to create a new company. If there is no coach at all a proper error message should be thrown instead of an error message.

**Comment by mluppi** [comment]
@martingwerder Currently, `lib-company` is hardcoded and a required dependency to create a new company and thus is needed to operate the platform initially. 

_My opinion is as follows:_
- It should be possible to create a company without a coach at all since coaches can be added later. In this case, the UI can inform the user that there are no coaches installed. Perhaps, there could be a list of default coaches (configurable) which are initialized when present upon creation of a company.
- In case the company-coach needs to execute something when the platform creates a company, this functionality should be moved to the platform itself.
- In case the company-coach stores general data associated with a company (or platform state concerning a company), this storage should be moved to the company-level.
